---
 name: Uninstall_DeskCent
  community.windows.win_psexec:
  executable: cmd.exe
  arguments: /c "C:\Program Files (x86)\DesktopCentral_Agent\Updates\DesktopCentralAgent.msi" /uninstall /quiet
  hosts: all