---
- hosts: all

  tasks:
  - name: Copy File
    win_copy:
      src: /tower-temp/localsetup
      dest: C:\Temp\
      
  - name: Install_DesktopCent
    win_package:
      path: 'C:\Temp\localsetup\DesktopCentralAgent.msi'
      arguments:
      - TRANSFORMS=C:\Temp\localsetup\DesktopCentralAgent.mst
      - ENABLESILENT=yes
      - REBOOT=ReallySuppress
      - INSTALLSOURCE=Manual
      - SERVER_ROOT_CRT="C:\Temp\localsetup\DMRootCA-Server.crt"
      - DS_ROOT_CRT="C:\Temp\localsetup\DMRootCA.crt"
      - /lv C:\Temp\localsetup\Agentinstalllog.txt
      state: present
      
      
      