---
- hosts: all

  tasks:
  - name: Copy File
    win_copy:
      src: /tower-temp/localsetup
      dest: C:\Temp\
      
  - name: Installl_DeskCent
    win_shell: C:\Temp\localsetup\ansible_setup.bat
    arg:
     - chdir: C:\Temp\localsetup